link:https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA[レポジトリのtopに戻る]

== 結論を先に述べる

わたしはカスタムGradleプラグインを開発しようとしてGradleプロジェクトを作った。２つのサブプロジェクトを持つComposite Buildの構成にした。コマンドラインのbashとテキストエディタEmacsで作った。そつなく動作するGradleプロジェクトを作ることができた。カスタムGradleプラグインのコードを発展させたくなった。IntelliJ IDEAにGradleプロジェクトをインポートしたくなった。GradleプロジェクトをIntelliJ IDEAで開いたが、うまくいかなかった。IDEAがクラスパスを正しく認識していない状態になり、何にもできなかった。どうすればGradleプロジェクトをIDEAにインポートすれば良いのか？「わからん！」と悩むばかりで2年経過した。だが今日、ようやく正しいやり方がわかった。

**完全に動作しているGradleプロジェクトをIDEAで開いたら、急がず、焦らず、５０秒ぐらいじっと待て！**

この５０秒間にIDEAはGradleプロジェクトのににある `build.gradle` ファイルを発見し、内容を解釈して、IDEAモジュールの望ましい設定を自動生成する。IDEAの準備ができたら `Load` ボタンを押せ！するとIDEAが与えられたGradleプロジェクトをそつなくIDEAプロジェクトとして再構成してくれる。

== 作業環境

* macOS 12.6
* Gradle 7.6
* IntelliJ IDEA Ultimate 2022.2.1
* Emacs 28.2

== サンプルコードのありか

下記UURLでサンプルコードを公開しています。

* https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA

この GitHubレポジトリには ４つのブランチが含まれています。

. link:https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA/tree/step1[ブランチ step1]
. link:https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA/tree/step2[ブランチ step2]
. link:https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA/tree/step3[ブランチ step3]
. link:https://github.com/kazurayam/GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA/tree/step4[ブランチ step4]

以下で４つのブランチについて説明します。

ブランチ step1 と step2 で、カスタムGradleプラグインを開発するためのGradleプロジェクトを作った。プラグイン開発のためのプロジェクトとそれを「リハーサル」する＝予行演習するためのプロジェクトと２つのプロジェクトからなるComposite Buildの構成にすることに成功した。step1とstep2を作るのにわたしは Terminalアプリケーション で bash とEmacsエディタを使い、あえてIntelliJ IDEAを使わなかった。つにぎ step3でGradleプロジェクトをIntelliJ IDEAに取り込むことを試みたができなかった。Composite Build構成のGradleプロジェクトをIntelliJ IDEAに結びつける正しい方法がわからなかった。この疑問に遭遇したのが２年ぐらい前。以来、悪戦苦闘した。そしてついに答えを見つけた。step4で答えを紹介する。

== step1

step1では、カスタムGradleプラグインを開発するためのGradleプラグインを一つ作りました。

`<rootDir>/plugin-project` ディレクトリを作ってカスタムGradleプラグインのプロジェクトを作った。`gradle init` コマンドを実行し`4: Gradle Plugin` を選択してサンプルコード一式を自動生成させた。

include::step1.adoc[]

== step2

step2では前述のstep1で開発したカスタムGradleプラグインを実際に利用して動作を確認するために、もう一つのGradleプラグインを作りました。

`<rootDir>/rehearsal-project` ディレクトリを追加してComposite Buildの構成にした。`rehearsal-project/build.gradle` ファイルがカスタムGradleプラグインを呼び出して実行できるようにした。`plugin-project` が開発したカスタムGradleプラグインを **Mavenレポジトリを経由せずに** 直接呼び出す。jarファイルを作ってMavenレポジトリに上げる手間を省くことで、リハーサルすなわち予行演習が素早くできるようにした。

include::step2.adoc[]

== step3

step2で一つのルートディレクトリの下に２つのGradleプロジェクトを包含するComposite Build構成のディレクトリを作ることに成功した。このファイルツリーをIntelliJ IDEAで開いて、まともなIDEAプロジェクトとして使えるようにしたかった。しかしうまくいかなかった。どのように失敗したかをstep3で説明します。

include::step3.adoc[]

== step4

さんざん悩んだあげく、Composite Build構成のGradleプロジェクトをIntelliJ IDEAで開いてまともなIDEAプロジェクトとして使えるように設定することについに成功した。教訓は「５０秒待て」だった。なんてこった。

include::step4.adoc[]

== 結論

わたしにとって長い苦難の道のりでした。
