ルートディレクトリ `GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA` の直下に、`plugin-project` ディレクトリに並ぶ形で `rehearsal-project` ディレクトリを作った。

[source]
----
$ baseName `pwd`
GradleCustomPlugin-CompositeBuild-linkToIntelliJIDEA

$ mkdir rehearsal-project

$ cd rehearsal-project

$ baseName `pwd`
rehearsal-project
----

そして `cd rehearsal-project` してから `gradle init` コマンドを実行した。basicなGradleプロジェクトを自動生成するためだ。

[source]
----
$ baseName `pwd`
rehearsal-project

$ gradle init

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 1

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 1

Generate build using new APIs and behavior (some features may change in the next
Project name (default: rehearsal-project):

> Task :init
Get more help with your project: Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples

BUILD SUCCESSFUL in 10s
2 actionable tasks: 2 executed
----

これによって `rehearsal-project` ディレクトリの下にGradleプロジェクトのコード一式が生成された。

[source]
----
$ baseName `pwd`
rehearsal-project

$ tree .
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── settings.gradle

3 directories, 6 files
----

わたは `rehearsal-project/settings.gradle` ファイルを次のように書き変えた。

[source]
----
include::../rehearsal-project/settings.gradle[]
----

`includeBuild('../plugin-project')` というクロージャー呼び出しに注目してほしい。これがGradleのドキュメントにおいて link:https://docs.gradle.org/current/userguide/composite_builds.html[Composite Build] と呼ばれているテクニックだ。これによって`plugin-project` プロジェクトが作成したカスタムGradleプラグインを `rehearsal-project` プロジェクトが直接に参照することができる。

わたしは `rehearsal-project/build.gradle` ファイルを次のように書き換えた。

[source]
----
include::../rehearsal-project/build.gradle[]
----

つまり `rehearsal-project` のGradleビルドが隣の `plugin-project` のカスタムGradleプラグインを使います、と宣言している。

カスタムGradleプラグインは実行時に `greeting` タスクをビルドに組み込むように作られている。だから実際に動かしてみよう。

[source]
----
$ baseName `pwd`
rehearsal-project

$ gradle greeting

> Task :greeting
Hello from plugin 'com.kazurayam.sample.greeting'

BUILD SUCCESSFUL in 2s
5 actionable tasks: 2 executed, 3 up-to-date
----

カスタムGradleプラグインが動いて "Hello " というメッセージを表示した。成功だ。

このように ブランチ step2 に格納されたコード一式はComposite Build構成のGradleプロジェクトになっていて、完全に動作することを確かめることができた。めでたし、めでたし。

以上のコードをわたしはbashシェルとテキストエディタで開発した。IntelliJ IDEAは使わなかった。次の step3 では step2 で作ったGradleプロジェクトをIntelliJ IDEAで開いて開発できるように設定することを試みた。.... ところがどっこい、うまくいかなかったんだ、これが。
